version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile_dev
      target: drupal_php
    container_name: ${PROJECT_NAME}_php-buster
    image: ${PROJECT_NAME}/php-buster:${PROJECT_TAG}
    volumes:
      - ./:${PROJECT_WORKDIR:-/srv/app}:rw

  nginx:
    build:
      context: .
      dockerfile: Dockerfile_dev
      target: drupal_nginx
    volumes:
      - ./web:${PROJECT_WORKDIR:-/srv/app}/web:ro
    networks:
      - default
      - traefik_gateway
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${NGINX_HOST}`)
      - traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}_nginx.tls=true
      - traefik.http.routers.${PROJECT_NAME}_nginx.tls.certresolver=le

networks:
  traefik_gateway:
    external:
      name: traefik_gateway
